name: Test - get LTS versions
description: Run transpiled version. Node 24 is by default enabled.

on:
  push:
    paths:
      - 'dist/**'
      - '.github/workflows/test-action.yaml'
  schedule:
    - cron: "0 8 * * 1"

jobs:
  get-lts-versions:
    name: Fetch LTS versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check for Golang LTS versions
        id: go
        uses: ./
        with:
          language: "go"
          versions_to_fetch: "3"

      - name: Print returned value for Golang
        shell: bash
        run: echo "${{ steps.go.outputs.lts_versions }}"

      - name: Check for Python LTS versions and verbose parameter
        id: python
        uses: ./
        with:
          language: "python"
          versions_to_fetch: "3"
          verbose: true

      - name: Print returned value for Python
        shell: bash
        run: echo "${{ steps.python.outputs.lts_versions }}"
